[[redirects]]
  from = "/articles/feed/"
  to = "/articles/feed/index.xml"
  status = 200

[[redirects]]
  from = "/podcast/feed/"
  to = "https://storage.googleapis.com/web-standards.ru/podcast/feed/index.xml"
  status = 200

[[redirects]]
  from = "/podcast/cover.png"
  to = "https://storage.googleapis.com/web-standards.ru/podcast/cover.png"
  status = 200

[[redirects]]
  from = "/podcast/episodes/*"
  to = "https://storage.googleapis.com/web-standards.ru/podcast/episodes/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404/index.html"
  status = 404
